[tools]
bun = "latest"
node = "24"

[tasks."dev"]
description = "Run dev build with portless"
run = "portless tasks bun -b next dev"

[tasks."db:migrate"]
description = "Migrate db"
run = "bunx prisma migrate dev"