import { BaseService } from '@api/core/services/base.service'
import { CreateWorkflowStateRequest, UpdateWorkflowStateRequest } from '@/types/dto/workflowStates.dto'
import { Resource } from '@api/core/types/api'
import { generateRandomString, toCamelCase } from '@/utils/string'
import { PoliciesService } from '@api/core/services/policies.service'
import { UserAction } from '@api/core/types/user'
import { WorkflowState } from '@prisma/client'
import { getWorkflowStatesByWorkspace } from '@/utils/workflowStates'
import { DEFAULT_WORKFLOW_STATE_NAMES } from '@/constants/workflowStates'

class WorkflowStatesService extends BaseService {
  async getAllWorkflowStates() {
    // Check if current user is authorized to access this resource
    const policyGate = new PoliciesService(this.user)
    policyGate.authorize(UserAction.Read, Resource.Tasks)

    let workflowStates: WorkflowState[] = await getWorkflowStatesByWorkspace(this.db, this.user.workspaceId)

    if (!workflowStates.length) {
      await this.setDefaultWorkflowStates()
      // Query workflowStates again because createMany only returns count and not an array of rows
      // also autogenerated ID field needs to be queried again anyway
      workflowStates = await getWorkflowStatesByWorkspace(this.db, this.user.workspaceId)
    }

    return workflowStates
  }

  async getOneWorkflowState(id: string) {
    const policyGate = new PoliciesService(this.user)
    policyGate.authorize(UserAction.Read, Resource.Tasks)

    return await this.db.workflowState.findFirst({ where: { id } })
  }

  async createWorkflowStates(data: CreateWorkflowStateRequest) {
    const policyGate = new PoliciesService(this.user)
    policyGate.authorize(UserAction.Create, Resource.Tasks)

    return await this.db.workflowState.create({
      data: {
        ...data,
        key: await this.generateKey(data.name),
        workspaceId: this.user.workspaceId,
      },
    })
  }

  async updateWorkflowState(id: string, data: UpdateWorkflowStateRequest) {
    const policyGate = new PoliciesService(this.user)
    policyGate.authorize(UserAction.Update, Resource.Tasks)

    return await this.db.workflowState.update({
      where: { id, workspaceId: this.user.workspaceId },
      data,
    })
  }

  /**
   * Sets default workflow states for a fresh workspace
   */
  private async setDefaultWorkflowStates() {
    return await this.db.workflowState.createMany({
      data: [
        { type: 'unstarted', name: DEFAULT_WORKFLOW_STATE_NAMES.unstarted, key: 'todo', workspaceId: this.user.workspaceId },
        {
          type: 'started',
          name: DEFAULT_WORKFLOW_STATE_NAMES.started,
          key: 'inProgress',
          workspaceId: this.user.workspaceId,
        },
        {
          type: 'completed',
          name: DEFAULT_WORKFLOW_STATE_NAMES.completed,
          key: 'completed',
          workspaceId: this.user.workspaceId,
        },
      ],
      skipDuplicates: true, //doesnt create if there is an existing workflowState.
    })
  }

  private async generateKey(name: string) {
    let key = toCamelCase(name)
    // If a key matching existing record exists, append a random
    // string since we have UQ_WorkflowState_workspaceId_key constraint
    const matchingKeyRecord = await this.db.workflowState.findFirst({ where: { key } })
    if (matchingKeyRecord) key += `-${generateRandomString(3)}`

    return key
  }
}

export default WorkflowStatesService
